@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

entity Shop

entity Cupcake{
topping
bund
}
entity Admin{
email
password
}
entity Order

entity Costumer{
email
password
}
entity OrderDetails{
quantity
}
entity Cart





Shop "1" -- "M" Cupcake
Cupcake "M" -- "1" Cart
OrderDetails "1" -- "1" Cupcake
OrderDetails "M" -- "1" Order
Order "M" -- "1" Costumer
Shop "1" -- "1" Admin
@enduml
