@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

object Shop
object Cupcake
object Admin
object Order
object Costumer




Shop *-- Cupcake
Shop *-- Admin
Shop *-- Order
Admin *-- Order
Costumer *-- Order
Order *-- Cupcake


@enduml